export ZSH="$HOME/.oh-my-zsh"
export EDITOR="$(which nvim)"
export VISUAL="$(which nvim)"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

ZSH_THEME="avit"
plugins=(git cp virtualenv)

alias vim='nvim'
alias v='nvim'

[ -f $ZSH/oh-my-zsh.sh ] && . $ZSH/oh-my-zsh.sh
[ -f $HOME/.personal_zshrc ] && . $HOME/.personal_zshrc

[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx -- vt1

# volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$PATH:$VOLTA_HOME/bin"

# golang
export PATH="$PATH:$HOME/.local/go/bin"
export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
export PATH=$HOME/.linkerd2/bin:$PATH

# React Native
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# k8s
export KUBECONFIG=$HOME/.kube/config:$HOME/personal/kubeconfig/home

# rocm
export LD_LIBRARY_PATH=/opt/rocm-6.3.4/lib
